### ISSUE TITLE
Quotation Template: Next Order Date Incorrect

### ISSUE THREAD

**Issue by DanielMaimba** [StrategicDimensions/Black-Forest-Bakery#2]
I added a new quotation template which is recurrent Week on Monday, and clicked the Calculate Button and the date added is 12/03/2018 instead of the 05/03/2018. It should be picking up the next date which is a monday and next mondays date is 05/03/2018.

<img width="1272" alt="screen shot 2018-03-01 at 09 49 35" src="https://user-images.githubusercontent.com/14073662/36833788-3cf518a2-1d39-11e8-85d5-ed8288a299f7.png">

**Comment by mdi-odoo** [comment]
Fixed in revision: https://github.com/StrategicDimensions/Black-Forest-Bakery/commit/e592d73eed9e612acc107f4a9b05eb5f7f7f10b1
