### ISSUE TITLE
Production List Report: not grouping and summing by Product

### ISSUE THREAD

**Issue by DanielMaimba** [StrategicDimensions/Black-Forest-Bakery#3]
The production list report is not grouping and summing by Product. In the test just conducted, I had 3 invoices with one product which has 100 qty each. The Production list report was supposed to show only 1 product with a total of 300 but it is printing every line separate.
<img width="1272" alt="screen shot 2018-03-01 at 09 49 35" src="https://user-images.githubusercontent.com/14073662/36834155-97e49656-1d3a-11e8-8939-11d997798a43.png">

**Comment by mdi-odoo** [comment]
Fixed in revision: https://github.com/StrategicDimensions/Black-Forest-Bakery/commit/b31cfd87a661566e0abbac8953ae9221b1a2db55
