### ISSUE TITLE
Sales Order Delivery Date: Not picking from Quotation Template

### ISSUE THREAD

**Issue by DanielMaimba** [StrategicDimensions/Black-Forest-Bakery#4]
If the sales order/quotation is automatically created from the quotation template, then the Delivery Date on the Sales order/quotation should be the date on the Next Order Date field before it was updated. So if the Next Order Date on the quotation template is 05/03/2018, then when the sales order is created, the Delivery Date should also be 05/03/2018.
<img width="1292" alt="screen shot 2018-03-01 at 10 25 02" src="https://user-images.githubusercontent.com/14073662/36834432-93183ad2-1d3b-11e8-877e-56d9a07add8a.png">

**Comment by mdi-odoo** [comment]
Fixed in revision: https://github.com/StrategicDimensions/Black-Forest-Bakery/commit/1a908f5c473069639fa31a4173d81e9e662fa025
