### ISSUE TITLE
URGENT: Quotation Template Next Order Date not updating

### ISSUE THREAD

**Issue by DanielMaimba** [StrategicDimensions/Black-Forest-Bakery#5]
The next order date on the quotation template is not updating when you click on the Calculate button or when you click on the Create Sales Order button. When you click it for the first time it updates, but when you click it after that it does not update anymore and orders that are created are all for one day.

![image](https://user-images.githubusercontent.com/14073662/37034157-005c614a-2151-11e8-8c1f-24efa0225896.png)

**Comment by mdi-odoo** [comment]
Fixed in revision: https://github.com/StrategicDimensions/Black-Forest-Bakery/commit/bb2aaaa9879bf4b060f6c68ab1238990acd8379c
