### ISSUE TITLE
 NOT WORKING: [IMP] Block adding the same product on quotation/sales order more than... 340d50b

### ISSUE THREAD

**Issue by DanielMaimba** [StrategicDimensions/Black-Forest-Bakery#6]
This item: 
[IMP] Block adding the same product on quotation/sales order more than...
340d50b
was deployed and used to work however it is not working anymore. Please review why it is not working.

**Comment by mdi-odoo** [comment]
Sale Order: https://blackforestbakery.odoo.com/web?debug#id=290&view_type=form&model=sale.order&menu_id=170&action=265 
contains duplicate product "SLICED RYE BREAD LARGE".

Remove that duplicate product and update database. It will work for sure.
