### ISSUE TITLE
Add Phone & Mobile on SO Form: The wrong field was added

### ISSUE THREAD

**Issue by DanielMaimba** [StrategicDimensions/Black-Forest-Bakery#7]
Requirement:
Please can you add the Phone and Mobile fields to the Sale Order form. These should pull the Phone and Mobile from the selected customer.

Issue:
Instead of the Phone & Mobile field to be added, you added Mobile and Email. Please update.
<img width="690" alt="screen shot 2018-03-14 at 07 08 59" src="https://user-images.githubusercontent.com/14073662/37384283-997a7654-2756-11e8-8d0e-858bebbfcf79.png">

**Comment by mdi-odoo** [comment]
Fixed in revision: https://github.com/StrategicDimensions/Black-Forest-Bakery/commit/969b51ded6a6ccb16ad5fc1402becc23051cde73
